name: CI

on:
  push:
    branches:  release-*

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v2
      - run:
          - git config user.name github-actions
          - git config user.email github-actions@github.com
          - git checkout -b workflow-$GITHUB_ACTION
          - versionSnapshot=`grep 'version=' gradle.properties | sed 's/version=\([^-]*\)/\1/'`
          - versionRelease=`echo $versionSnapshot | sed 's/\([^-]*\)-SNAPSHOT/\1/'`
          - versionSnapshotNext=`echo $versionSnapshot | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e'`
          - echo "$versionSnapshot -> $versionRelease  -> $versionSnapshotNext"
          - sed -i "s/version=$versionSnapshot/version=$versionRelease/" gradle.properties
          - git commit -am "[skip-ci] Generate release version"
          - sed -i "s/version=$versionRelease/version=$versionSnapshotNext/" gradle.properties
          - git commit -am "[skip-ci] Generate next snapshot version"
          - git push origin HEAD
